version: '3'

volumes:
  data:
  uploads:

networks:
  transcendence:

services:
  front:
    container_name: frontend
    build:
      context: ./apps/website/
      target: run
    command: pnpm run dev
    environment:
      NODE_ENV: development
    volumes:
      - uploads:/app/uploads
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - transcendence
    depends_on:
      - backend

  database:
    image: postgres:13
    container_name: postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
    networks:
      - transcendence

  backend:
    build:
      context: ./apps/server/
      target: dev
    container_name: backend
    command: pnpm run start:dev
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?schema=public
    env_file:
      - ./.env
    volumes:
      - uploads:/app/uploads
    ports:
      - "4000:4000"
      - "5555:5555"
    restart: unless-stopped
    networks:
      - transcendence
    depends_on:
      - database
