version: '3.8'

volumes:
  data:
  uploads:

networks:
  transcendence:

services:
  front:
    container_name: frontend
    build:
      context: ./apps/website/
      target: runner
    command: npm run dev
    entrypoint: ./docker-entrypoint.sh
    environment:
      NODE_ENV: development
    volumes:
      - ./apps/website:/app
      - uploads:/app/public/images
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - transcendence
    depends_on:
      - backend

  database:
    image: postgres:13
    container_name: postgres
    ports:
      - 5432:5432
    env_file: ./apps/server/.env
    networks:
      - transcendence

  backend:
    build:
      context: ./apps/server/
      target: dev
    container_name: backend
    stdin_open: true
    tty: true
    command: sh -c "npx prisma migrate dev --name migration && npm run start:dev"
    entrypoint: ./docker-entrypoint.sh
    env_file: ./apps/server/.env
    volumes:
      - ./apps/server:/app
      - uploads:/app/uploads
    ports:
      - "4000:4000"
      - "5555:5555"
    restart: unless-stopped
    networks:
      - transcendence
    depends_on:
      - database

