version: '3.8'

volumes:
  data:
  uploads:

networks:
  backend:

services:
# FRONTEND
  front:
    container_name: frontend
    build:
      context: ./apps/website/
      target: runner
    command: npm run dev
    entrypoint: ./docker-entrypoint.sh
    environment:
      NODE_ENV: development
    volumes:
      - ./apps/website:/app
      - uploads:/app/uploads
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend

  database:
    image: postgres:13
    container_name: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - backend

  backend:
    build:
      context: ./apps/server/
      target: dev
    container_name: backend
    command: npm run start:dev
    entrypoint: ./docker-entrypoint.sh
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nest
    volumes:
      - ./apps/server:/app
      - uploads:/app/uploads
    ports:
      - "4000:4000"
      - "5555:5555"
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - database

