version: '3.8'

volumes:
  data:
  uploads:

networks:
  backend:

services:
# FRONTEND
  front:
    image: node:lts-alpine
    container_name: frontend
    working_dir: /app
    command: sh -c "npm install 
                    && npm run build
                    && npm install -g serve 
                    && serve -s build -l 3000"
    volumes:
      - ./apps/website:/app
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - back
  test-db:
    image: postgres:13
    container_name: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - backend

  backend:
    build:
      context: ./apps/server/
      target: dev
    container_name: backend
    command: npm run start:dev
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nest
    volumes:
      - ./apps/server:/app
    ports:
      - "4000:4000"
      - "5555:5555"
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - test-db