import Head from 'next/head';
import Field from '../components/Field.tsx';

export default function Home() {
	return (
		<>
			<Head>
				<title>cool site</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<body>
				<Field id="login" name="login" placeholder="Enter login" size="16"/>
				<Field id="password" name="password" placeholder="password" size="16"/>
			</body>
		</>
	);
}
