import Head from 'next/head'
import LoginForm from '@/components/Form.tsx'
import formStyle from "@/styles/form.module.css"

export default function Home() {
return (
	<>
		<Head>
			<title>cool site</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<LoginForm/>
	</>
)
}
